[package]
name = "optz"
version = "0.3.0"
edition = "2024"
description = "A no-magic option parser for Rust"
license = "MIT"
authors = ["Josh Voigts <joshvoigts@gmail.com>"]
repository = "https://github.com/joshvoigts/optz"
readme = "README.md"

[dependencies]
